# Generated by Django 3.2.8 on 2023-04-28 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='valid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='valid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.judge'),
        ),
    ]
