# Generated by Django 3.2.8 on 2023-04-27 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
