# Generated by Django 3.2.8 on 2023-05-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_blogs_related_problem'),
        ('problems', '0002_problem_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='blog',
        ),
        migrations.AddField(
            model_name='problem',
            name='blog',
            field=models.ManyToManyField(blank=True, to='blogs.Blogs'),
        ),
    ]
