# Generated by Django 3.2.8 on 2023-04-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20230428_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.judge'),
        ),
    ]
