# Generated by Django 3.2.8 on 2023-05-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editorials', '0002_auto_20230505_1632'),
        ('problems', '0003_auto_20230505_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='editorial',
        ),
        migrations.AddField(
            model_name='problem',
            name='editorial',
            field=models.ManyToManyField(blank=True, to='editorials.Editorials'),
        ),
    ]
