# Generated by Django 3.2.8 on 2023-04-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='judge',
            field=models.CharField(default='toph', max_length=255),
            preserve_default=False,
        ),
    ]
