# Generated by Django 3.2.8 on 2023-05-12 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='utl',
            new_name='url',
        ),
    ]
