# Generated by Django 3.2.8 on 2023-05-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestants', '0002_rename_utl_profile_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.ManyToManyField(blank=True, to='contestants.User_sites'),
        ),
    ]
