# Generated by Django 3.2.8 on 2023-05-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_problem_blog'),
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='related_problem',
            field=models.ManyToManyField(blank=True, to='problems.Problem'),
        ),
    ]
