# Generated by Django 3.2.8 on 2023-05-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20230505_1628'),
        ('editorials', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorials',
            name='problem',
        ),
        migrations.AddField(
            model_name='editorials',
            name='related_problem',
            field=models.ManyToManyField(blank=True, to='problems.Problem'),
        ),
    ]
