# Generated by Django 4.2 on 2023-04-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20230428_2223'),
        ('editorials', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='add_editorials',
            name='tags',
            field=models.ManyToManyField(to='problems.tag'),
        ),
    ]
