# Generated by Django 4.2 on 2023-04-29 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20230428_2223'),
        ('editorials', '0002_delete_tag_alter_add_editorials_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_editorials',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='problems.judge'),
        ),
    ]
